# -*- Makefile -*- Force tab character insertion instead of space: 
# Comment

# WRITING MAKE FILE
# Automates c/c++ build process
# FILENAME = [Makefile | makefile]

VARIABLE = VALUE

# Convention to make all target(s)
all: DEPENDENC(Y|IES) 

# Format
TARGET: DEPENDENC(Y|IES)
	ACTION(S)

# Convention to remove unneeded (object target) files
clean:
	rm -f *.o target(s)
